"""Curated seed data for development.

Real artists, real museums (with real coordinates), real artworks assigned to
their actual holding institutions. Wikidata Q-IDs are real, so when a future
Wikidata ETL runs, it will upsert the same rows naturally.

Image URLs point at Wikimedia Commons.
"""

from __future__ import annotations

from typing import Any

ARTISTS: list[dict[str, Any]] = [
    {
        "wikidata_id": "Q762",
        "name": "Leonardo da Vinci",
        "birth_year": 1452,
        "death_year": 1519,
        "nationality": "Italian",
        "movement": "Renaissance",
    },
    {
        "wikidata_id": "Q5582",
        "name": "Vincent van Gogh",
        "birth_year": 1853,
        "death_year": 1890,
        "nationality": "Dutch",
        "movement": "Post-Impressionism",
    },
    {
        "wikidata_id": "Q5593",
        "name": "Pablo Picasso",
        "birth_year": 1881,
        "death_year": 1973,
        "nationality": "Spanish",
        "movement": "Cubism",
    },
    {
        "wikidata_id": "Q296",
        "name": "Claude Monet",
        "birth_year": 1840,
        "death_year": 1926,
        "nationality": "French",
        "movement": "Impressionism",
    },
    {
        "wikidata_id": "Q5588",
        "name": "Frida Kahlo",
        "birth_year": 1907,
        "death_year": 1954,
        "nationality": "Mexican",
        "movement": "Surrealism",
    },
    {
        "wikidata_id": "Q5586",
        "name": "Katsushika Hokusai",
        "birth_year": 1760,
        "death_year": 1849,
        "nationality": "Japanese",
        "movement": "Ukiyo-e",
    },
    {
        "wikidata_id": "Q30755",
        "name": "Auguste Rodin",
        "birth_year": 1840,
        "death_year": 1917,
        "nationality": "French",
        "movement": "Realism",
    },
    {
        "wikidata_id": "Q224944",
        "name": "Yayoi Kusama",
        "birth_year": 1929,
        "death_year": None,
        "nationality": "Japanese",
        "movement": "Contemporary",
    },
    {
        "wikidata_id": "Q297",
        "name": "Diego Velázquez",
        "birth_year": 1599,
        "death_year": 1660,
        "nationality": "Spanish",
        "movement": "Baroque",
    },
    {
        "wikidata_id": "Q47551",
        "name": "Sandro Botticelli",
        "birth_year": 1445,
        "death_year": 1510,
        "nationality": "Italian",
        "movement": "Renaissance",
    },
    {
        "wikidata_id": "Q5598",
        "name": "Rembrandt van Rijn",
        "birth_year": 1606,
        "death_year": 1669,
        "nationality": "Dutch",
        "movement": "Dutch Golden Age",
    },
    {
        "wikidata_id": "Q5577",
        "name": "Salvador Dalí",
        "birth_year": 1904,
        "death_year": 1989,
        "nationality": "Spanish",
        "movement": "Surrealism",
    },
    {
        "wikidata_id": "Q41264",
        "name": "Johannes Vermeer",
        "birth_year": 1632,
        "death_year": 1675,
        "nationality": "Dutch",
        "movement": "Dutch Golden Age",
    },
    {
        "wikidata_id": "Q5592",
        "name": "Michelangelo",
        "birth_year": 1475,
        "death_year": 1564,
        "nationality": "Italian",
        "movement": "Renaissance",
    },
    {
        "wikidata_id": "Q243149",
        "name": "Georgia O'Keeffe",
        "birth_year": 1887,
        "death_year": 1986,
        "nationality": "American",
        "movement": "Modernism",
    },
]


MUSEUMS: list[dict[str, Any]] = [
    {
        "wikidata_id": "Q19675",
        "name": "Louvre",
        "city": "Paris",
        "country": "France",
        "latitude": 48.8606,
        "longitude": 2.3376,
        "website": "https://www.louvre.fr",
    },
    {
        "wikidata_id": "Q23402",
        "name": "Musée d'Orsay",
        "city": "Paris",
        "country": "France",
        "latitude": 48.8600,
        "longitude": 2.3266,
        "website": "https://www.musee-orsay.fr",
    },
    {
        "wikidata_id": "Q188740",
        "name": "Museum of Modern Art",
        "city": "New York",
        "country": "United States",
        "latitude": 40.7614,
        "longitude": -73.9776,
        "website": "https://www.moma.org",
    },
    {
        "wikidata_id": "Q160236",
        "name": "Metropolitan Museum of Art",
        "city": "New York",
        "country": "United States",
        "latitude": 40.7794,
        "longitude": -73.9632,
        "website": "https://www.metmuseum.org",
    },
    {
        "wikidata_id": "Q193375",
        "name": "Tate Modern",
        "city": "London",
        "country": "United Kingdom",
        "latitude": 51.5076,
        "longitude": -0.0994,
        "website": "https://www.tate.org.uk/visit/tate-modern",
    },
    {
        "wikidata_id": "Q180788",
        "name": "National Gallery",
        "city": "London",
        "country": "United Kingdom",
        "latitude": 51.5089,
        "longitude": -0.1283,
        "website": "https://www.nationalgallery.org.uk",
    },
    {
        "wikidata_id": "Q160112",
        "name": "Museo del Prado",
        "city": "Madrid",
        "country": "Spain",
        "latitude": 40.4138,
        "longitude": -3.6921,
        "website": "https://www.museodelprado.es",
    },
    {
        "wikidata_id": "Q460889",
        "name": "Museo Reina Sofía",
        "city": "Madrid",
        "country": "Spain",
        "latitude": 40.4080,
        "longitude": -3.6943,
        "website": "https://www.museoreinasofia.es",
    },
    {
        "wikidata_id": "Q173799",
        "name": "Uffizi Gallery",
        "city": "Florence",
        "country": "Italy",
        "latitude": 43.7678,
        "longitude": 11.2553,
        "website": "https://www.uffizi.it",
    },
    {
        "wikidata_id": "Q190804",
        "name": "Rijksmuseum",
        "city": "Amsterdam",
        "country": "Netherlands",
        "latitude": 52.3600,
        "longitude": 4.8852,
        "website": "https://www.rijksmuseum.nl",
    },
    {
        "wikidata_id": "Q224124",
        "name": "Van Gogh Museum",
        "city": "Amsterdam",
        "country": "Netherlands",
        "latitude": 52.3584,
        "longitude": 4.8811,
        "website": "https://www.vangoghmuseum.nl",
    },
    {
        "wikidata_id": "Q3329419",
        "name": "Museo Frida Kahlo",
        "city": "Mexico City",
        "country": "Mexico",
        "latitude": 19.3550,
        "longitude": -99.1625,
        "website": "https://www.museofridakahlo.org.mx",
    },
]


ARTWORKS: list[dict[str, Any]] = [
    # Leonardo — Louvre
    {
        "wikidata_id": "Q12418",
        "title": "Mona Lisa",
        "artist_wikidata_id": "Q762",
        "museum_wikidata_id": "Q19675",
        "year": 1503,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg?width=600",
    },
    {
        "wikidata_id": "Q47271",
        "title": "The Virgin and Child with Saint Anne",
        "artist_wikidata_id": "Q762",
        "museum_wikidata_id": "Q19675",
        "year": 1503,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Leonardo_da_Vinci_-_Virgin_and_Child_with_St_Anne_C2RMF_retouched.jpg?width=600",
    },
    # Van Gogh — MoMA, Van Gogh Museum, National Gallery
    {
        "wikidata_id": "Q45585",
        "title": "The Starry Night",
        "artist_wikidata_id": "Q5582",
        "museum_wikidata_id": "Q188740",
        "year": 1889,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg?width=600",
    },
    {
        "wikidata_id": "Q1144555",
        "title": "The Bedroom",
        "artist_wikidata_id": "Q5582",
        "museum_wikidata_id": "Q224124",
        "year": 1888,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg?width=600",
    },
    {
        "wikidata_id": "Q763304",
        "title": "Wheatfield with Crows",
        "artist_wikidata_id": "Q5582",
        "museum_wikidata_id": "Q224124",
        "year": 1890,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Vincent_van_Gogh_-_Wheatfield_with_crows_-_Google_Art_Project.jpg?width=600",
    },
    {
        "wikidata_id": "Q161763",
        "title": "Sunflowers",
        "artist_wikidata_id": "Q5582",
        "museum_wikidata_id": "Q180788",
        "year": 1888,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Vincent_Willem_van_Gogh_127.jpg?width=600",
    },
    # Picasso — MoMA + Reina Sofía
    {
        "wikidata_id": "Q166747",
        "title": "Les Demoiselles d'Avignon",
        "artist_wikidata_id": "Q5593",
        "museum_wikidata_id": "Q188740",
        "year": 1907,
        "kind": "painting",
        "image_url": "https://en.wikipedia.org/wiki/Special:FilePath/Les_Demoiselles_d%27Avignon.jpg?width=600",
    },
    {
        "wikidata_id": "Q175036",
        "title": "Guernica",
        "artist_wikidata_id": "Q5593",
        "museum_wikidata_id": "Q460889",
        "year": 1937,
        "kind": "painting",
        "image_url": "https://en.wikipedia.org/wiki/Special:FilePath/PicassoGuernica.jpg?width=800",
    },
    # Monet — Musée d'Orsay + MoMA
    {
        "wikidata_id": "Q1196822",
        "title": "The Magpie",
        "artist_wikidata_id": "Q296",
        "museum_wikidata_id": "Q23402",
        "year": 1869,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Claude_Monet_-_The_Magpie_-_Google_Art_Project.jpg?width=600",
    },
    {
        "wikidata_id": "Q3402069",
        "title": "Poppies",
        "artist_wikidata_id": "Q296",
        "museum_wikidata_id": "Q23402",
        "year": 1873,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Claude_Monet_-_Coquelicots.jpg?width=600",
    },
    {
        "wikidata_id": "Q1062810",
        "title": "Water Lilies",
        "artist_wikidata_id": "Q296",
        "museum_wikidata_id": "Q188740",
        "year": 1916,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg?width=600",
    },
    # Frida Kahlo — Museo Frida Kahlo
    {
        "wikidata_id": "Q5717159",
        "title": "Viva la Vida, Watermelons",
        "artist_wikidata_id": "Q5588",
        "museum_wikidata_id": "Q3329419",
        "year": 1954,
        "kind": "painting",
        "image_url": "https://en.wikipedia.org/wiki/Special:FilePath/Viva-la-vida.jpg?width=600",
    },
    # Hokusai — Met (one of many casts/prints)
    {
        "wikidata_id": "Q643411",
        "title": "The Great Wave off Kanagawa",
        "artist_wikidata_id": "Q5586",
        "museum_wikidata_id": "Q160236",
        "year": 1831,
        "kind": "other",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/The_Great_Wave_off_Kanagawa.jpg?width=600",
    },
    {
        "wikidata_id": "Q1404912",
        "title": "Fine Wind, Clear Morning",
        "artist_wikidata_id": "Q5586",
        "museum_wikidata_id": "Q160236",
        "year": 1830,
        "kind": "other",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Red_Fuji_southern_wind_clear_morning.jpg?width=600",
    },
    # Rodin — Met (cast of The Thinker)
    {
        "wikidata_id": "Q4558504",
        "title": "The Thinker",
        "artist_wikidata_id": "Q30755",
        "museum_wikidata_id": "Q160236",
        "year": 1880,
        "kind": "sculpture",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/The_Thinker%2C_Auguste_Rodin.jpg?width=600",
    },
    # Yayoi Kusama — Tate Modern (Infinity Mirror Rooms touring)
    {
        "wikidata_id": "Q66344922",
        "title": "Infinity Mirrored Room — Filled with the Brilliance of Life",
        "artist_wikidata_id": "Q224944",
        "museum_wikidata_id": "Q193375",
        "year": 2011,
        "kind": "other",
        "image_url": None,
    },
    # Velázquez — Prado
    {
        "wikidata_id": "Q170351",
        "title": "Las Meninas",
        "artist_wikidata_id": "Q297",
        "museum_wikidata_id": "Q160112",
        "year": 1656,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Las_Meninas%2C_by_Diego_Vel%C3%A1zquez%2C_from_Prado_in_Google_Earth.jpg?width=600",
    },
    {
        "wikidata_id": "Q1220251",
        "title": "The Surrender of Breda",
        "artist_wikidata_id": "Q297",
        "museum_wikidata_id": "Q160112",
        "year": 1635,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Vel%C3%A1zquez_-_de_Breda_o_Las_Lanzas_%28Museo_del_Prado%2C_1634-35%29.jpg?width=800",
    },
    # Botticelli — Uffizi
    {
        "wikidata_id": "Q201957",
        "title": "The Birth of Venus",
        "artist_wikidata_id": "Q47551",
        "museum_wikidata_id": "Q173799",
        "year": 1485,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg?width=800",
    },
    {
        "wikidata_id": "Q193404",
        "title": "Primavera",
        "artist_wikidata_id": "Q47551",
        "museum_wikidata_id": "Q173799",
        "year": 1482,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Botticelli-primavera.jpg?width=800",
    },
    # Rembrandt — Rijksmuseum + National Gallery
    {
        "wikidata_id": "Q219831",
        "title": "The Night Watch",
        "artist_wikidata_id": "Q5598",
        "museum_wikidata_id": "Q190804",
        "year": 1642,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/The_Night_Watch_-_HD.jpg?width=800",
    },
    {
        "wikidata_id": "Q700430",
        "title": "The Jewish Bride",
        "artist_wikidata_id": "Q5598",
        "museum_wikidata_id": "Q190804",
        "year": 1667,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Rembrandt_Harmensz._van_Rijn_-_Portret_van_een_paar_als_oudtestamentische_figuren%2C_genaamd_%27Het_Joodse_bruidje%27_-_Google_Art_Project.jpg?width=600",
    },
    {
        "wikidata_id": "Q467279",
        "title": "Self-Portrait at the Age of 63",
        "artist_wikidata_id": "Q5598",
        "museum_wikidata_id": "Q180788",
        "year": 1669,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg?width=600",
    },
    # Dalí — MoMA + Reina Sofía
    {
        "wikidata_id": "Q160064",
        "title": "The Persistence of Memory",
        "artist_wikidata_id": "Q5577",
        "museum_wikidata_id": "Q188740",
        "year": 1931,
        "kind": "painting",
        "image_url": "https://en.wikipedia.org/wiki/Special:FilePath/The_Persistence_of_Memory.jpg?width=600",
    },
    # Vermeer — Rijksmuseum
    {
        "wikidata_id": "Q172888",
        "title": "The Milkmaid",
        "artist_wikidata_id": "Q41264",
        "museum_wikidata_id": "Q190804",
        "year": 1660,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg?width=600",
    },
    {
        "wikidata_id": "Q505373",
        "title": "Woman in Blue Reading a Letter",
        "artist_wikidata_id": "Q41264",
        "museum_wikidata_id": "Q190804",
        "year": 1663,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Johannes_Vermeer_-_Woman_reading_a_letter_-_Google_Art_Project.jpg?width=600",
    },
    # Michelangelo — Uffizi
    {
        "wikidata_id": "Q731538",
        "title": "Doni Tondo",
        "artist_wikidata_id": "Q5592",
        "museum_wikidata_id": "Q173799",
        "year": 1507,
        "kind": "painting",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Michelangelo_Buonarroti_-_Tondo_Doni_-_Google_Art_Project.jpg?width=600",
    },
    # Georgia O'Keeffe — Met
    {
        "wikidata_id": "Q3677528",
        "title": "Cow's Skull: Red, White, and Blue",
        "artist_wikidata_id": "Q243149",
        "museum_wikidata_id": "Q160236",
        "year": 1931,
        "kind": "painting",
        "image_url": "https://en.wikipedia.org/wiki/Special:FilePath/Cow%27s_Skull-_Red%2C_White%2C_and_Blue_by_Georgia_O%27Keeffe.jpg?width=600",
    },
    {
        "wikidata_id": "Q4924260",
        "title": "Black Iris",
        "artist_wikidata_id": "Q243149",
        "museum_wikidata_id": "Q160236",
        "year": 1926,
        "kind": "painting",
        "image_url": "https://en.wikipedia.org/wiki/Special:FilePath/Black_Iris_by_Georgia_O%27Keeffe_1926.jpg?width=600",
    },
]
